DROP DATABASE IF EXISTS STATSDB;

CREATE DATABASE STATSDB;

USE STATSDB;

CREATE TABLE STATS(
    GUESS_ID INT NOT NULL AUTO_INCREMENT,
    GUESS INT NOT NULL,
    PRIMARY KEY(GUESS_ID)
);

INSERT INTO STATS (GUESS) VALUES;